version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - "8000:8000" 
    env_file:
      - ./server/.env 
    networks:
      - school_network
    volumes:
      - ./server:/app  
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container
    ports:
      - "3000:3000"  
    networks:
      - school_network
    volumes:
      - ./client:/app 

networks:
  school_network:
    driver: bridge  
